const messages: Record<string, string> = {
  party_request_invalid: 'Действие уже недоступно. Обновите группу.',
  party_character_not_found: 'Персонаж больше недоступен.',
  party_invite_not_found: 'Приглашение больше недоступно.',
  party_idempotency_conflict: 'Группа уже изменилась. Обновите состав.',
  party_invalid_state: 'Сейчас это действие недоступно.',
  party_load_failed: 'Не удалось загрузить группу.',
  party_leave_failed: 'Не удалось покинуть группу.',
  party_kick_failed: 'Не удалось исключить участника.',
  party_transfer_failed: 'Не удалось передать лидерство.',
  party_disband_failed: 'Не удалось распустить группу.',
  party_not_leader: 'Это может сделать только лидер группы.',
  party_full: 'В группе уже пять участников.',
  party_already_in_party: 'Персонаж уже состоит в группе.',
  party_invite_expired: 'Срок приглашения истёк. Попросите лидера отправить новое.',
  party_target_not_friend: 'Сначала добавьте персонажа в друзья.',
  party_not_found: 'Группа больше не существует.',
  dungeon_party_required: 'Сначала создайте группу.',
  dungeon_not_leader: 'Забег запускает лидер группы.',
  dungeon_level_required: 'Для этого подземелья нужен более высокий уровень.',
  dungeon_travel_in_progress: 'Сначала завершите путешествие.',
  dungeon_invalid_location: 'Всем участникам нужно быть у входа в подземелье.',
  dungeon_member_cannot_enter: 'Один из участников пока не может войти. Проверьте уровень, здоровье и текущую активность.',
  dungeon_encounter_active: 'Сначала завершите текущий бой.',
  dungeon_encounter_not_ready: 'Группа пока не готова к следующему бою. Обновите забег.',
  dungeon_member_not_in_party: 'Для этого действия нужно состоять в группе забега.',
  dungeon_member_not_in_run: 'Сначала войдите в забег.',
  dungeon_run_not_found: 'Забег больше недоступен.',
  dungeon_run_already_active: 'У группы уже есть другой активный забег. Сначала завершите или покиньте его.',
  friend_request_pending: 'Заявка уже отправлена.',
  friend_request_already_decided: 'Эта заявка уже обработана. Обновите список друзей.',
  friend_request_not_found: 'Заявка больше недоступна.',
  friend_self: 'Нельзя добавить самого себя в друзья.',
  friend_request_cancel_failed: 'Не удалось отменить заявку. Обновите список и попробуйте ещё раз.',
  friend_already_friends: 'Этот персонаж уже в друзьях.',
  network_unavailable: 'Нет связи с сервером. Попробуйте ещё раз.',
}

export function socialErrorMessage(code: string): string {
  return messages[code] ?? 'Не удалось выполнить действие. Попробуйте ещё раз.'
}
