const messages: Record<string, string> = {
  party_request_invalid: 'Некорректное действие с группой. Обновите состав и повторите.',
  party_character_not_found: 'Персонаж больше недоступен.',
  party_invite_not_found: 'Приглашение больше не существует.',
  party_idempotency_conflict: 'Состояние группы уже изменилось другим запросом. Обновите состав.',
  party_invalid_state: 'Это действие сейчас недоступно для текущего состояния группы.',
  party_load_failed: 'Не удалось загрузить состояние группы.',
  party_leave_failed: 'Не удалось покинуть группу.',
  party_kick_failed: 'Не удалось исключить участника.',
  party_transfer_failed: 'Не удалось передать лидерство.',
  party_disband_failed: 'Не удалось распустить группу.',
  party_not_leader: 'Это действие выполняет лидер группы.',
  party_full: 'В группе уже пять участников.',
  party_already_in_party: 'Персонаж уже состоит в группе.',
  party_invite_expired: 'Приглашение истекло. Попросите лидера отправить новое.',
  party_target_not_friend: 'Сначала добавьте персонажа в друзья.',
  party_not_found: 'Группа больше не существует.',
  dungeon_party_required: 'Создайте группу перед входом в подземелье.',
  dungeon_not_leader: 'Забег запускает лидер группы.',
  dungeon_level_required: 'Уровень героя ниже минимального уровня этого подземелья.',
  dungeon_travel_in_progress: 'Сначала завершите текущий переход.',
  dungeon_invalid_location: 'Всем участникам нужно переместиться ко входу в подземелье.',
  dungeon_member_cannot_enter: 'Участник не готов к входу: проверьте уровень, здоровье и текущую активность.',
  dungeon_encounter_active: 'Сначала завершите текущий бой.',
  dungeon_encounter_not_ready: 'Обновите состояние забега и проверьте готовность участников.',
  dungeon_member_not_in_party: 'Для этого действия нужно состоять в группе забега.',
  dungeon_member_not_in_run: 'Сначала войдите в забег.',
  dungeon_run_not_found: 'Забег больше недоступен.',
  dungeon_run_already_active: 'У группы уже есть активный забег в другом подземелье. Сначала завершите или покиньте его.',
  friend_request_pending: 'Заявка уже отправлена.',
  friend_request_already_decided: 'Эта заявка уже обработана. Обновите список друзей.',
  friend_request_not_found: 'Заявка больше не существует.',
  friend_self: 'Нельзя добавить самого себя в друзья.',
  friend_request_cancel_failed: 'Не удалось отменить заявку. Обновите список и попробуйте ещё раз.',
  friend_already_friends: 'Этот персонаж уже в друзьях.',
  network_unavailable: 'Нет связи с сервером. Попробуйте ещё раз.',
}

export function socialErrorMessage(code: string): string {
  return messages[code] ?? 'Не удалось выполнить действие. Обновите состояние и попробуйте ещё раз.'
}
