// <auto-generated />
using System;
using Elyndor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elyndor.Infrastructure.Persistence.Migrations;

    [DbContext(typeof(GameDbContext))]
    [Migration("20260830075709_PhaseOneIdentityWorld")]
    partial class PhaseOneIdentityWorld
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elyndor.Core.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreationRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("GenderId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_account_id");

                    b.HasIndex("CreationRequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_creation_request_id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_normalized_name");

                    b.ToTable("characters", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_telegram_user_id");

                    b.ToTable("accounts", "game");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterLocation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("CharacterId")
                        .HasName("pk_character_locations");

                    b.ToTable("character_locations", "game");
                });

            modelBuilder.Entity("Elyndor.Core.World.TravelOperation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultLocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ResultVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetLocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CharacterId", "RequestId")
                        .HasName("pk_travel_operations");

                    b.ToTable("travel_operations", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Characters.Character", b =>
                {
                    b.HasOne("Elyndor.Core.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_accounts_account_id");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterLocation", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("Elyndor.Core.World.CharacterLocation", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_locations_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.World.TravelOperation", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_travel_operations_characters_character_id");
                });
#pragma warning restore 612, 618
        }
    }
