// <auto-generated />
using System;
using Elyndor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elyndor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260912061031_AddAfkFarmIntervalGrants")]
    partial class AddAfkFarmIntervalGrants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elyndor.Core.Administration.AdminCommandAudit", b =>
                {
                    b.Property<long>("UpdateId")
                        .HasColumnType("bigint");

                    b.Property<long>("AdministratorTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long?>("TargetTelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("UpdateId")
                        .HasName("pk_admin_command_audits");

                    b.HasIndex("AdministratorTelegramUserId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_admin_command_audits_administrator_received_at");

                    b.HasIndex("TargetTelegramUserId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_admin_command_audits_target_received_at");

                    b.ToTable("admin_command_audits", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Afk.AfkFarmIntervalGrant", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("IntervalIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kills")
                        .HasColumnType("integer");

                    b.Property<string>("LootJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("SessionId", "IntervalIndex")
                        .HasName("pk_afk_farm_interval_grants");

                    b.ToTable("afk_farm_interval_grants", "game", t =>
                        {
                            t.HasCheckConstraint("ck_afk_farm_interval_grants_loot_json", "jsonb_typeof(\"LootJson\") = 'array'");

                            t.HasCheckConstraint("ck_afk_farm_interval_grants_non_negative_rewards", "\"Kills\" >= 0 AND \"XpEarned\" >= 0 AND \"GoldEarned\" >= 0");

                            t.HasCheckConstraint("ck_afk_farm_interval_grants_positive_window", "\"EndedAtUtc\" > \"StartedAtUtc\"");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Afk.AfkFarmSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BalanceVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("CharacterSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StopReason")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_afk_farm_sessions");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("uq_afk_farm_sessions_active_character_id")
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("CharacterId", "CreatedAtUtc")
                        .HasDatabaseName("ix_afk_farm_sessions_character_created_at_utc");

                    b.HasIndex("Status", "EndsAtUtc")
                        .HasDatabaseName("ix_afk_farm_sessions_status_ends_at_utc");

                    b.ToTable("afk_farm_sessions", "game", t =>
                        {
                            t.HasCheckConstraint("ck_afk_farm_sessions_positive_duration", "\"EndsAtUtc\" > \"StartedAtUtc\"");

                            t.HasCheckConstraint("ck_afk_farm_sessions_processing_window", "\"LastProcessedAtUtc\" >= \"StartedAtUtc\" AND \"LastProcessedAtUtc\" <= \"EndsAtUtc\"");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreationRequestId")
                        .HasColumnType("uuid");

                    b.Property<long>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("GenderId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("Gold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PublicCode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_account_id");

                    b.HasIndex("CreationRequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_creation_request_id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_normalized_name");

                    b.HasIndex("PublicCode")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_public_code");

                    b.ToTable("characters", "game", t =>
                        {
                            t.HasCheckConstraint("ck_characters_experience_non_negative", "\"Experience\" >= 0");

                            t.HasCheckConstraint("ck_characters_gold_non_negative", "\"Gold\" >= 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Characters.CharacterMutation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MutationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CommittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CharacterId", "MutationId")
                        .HasName("pk_character_mutations");

                    b.HasIndex("CharacterId", "CommittedAtUtc")
                        .HasDatabaseName("ix_character_mutations_character_committed_at");

                    b.ToTable("character_mutations", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Characters.CharacterVitals", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckpointedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ContextStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentHp")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("CurrentResource")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.HasKey("CharacterId")
                        .HasName("pk_character_vitals");

                    b.ToTable("character_vitals", "game", t =>
                        {
                            t.HasCheckConstraint("ck_character_vitals_hp_non_negative", "\"CurrentHp\" >= 0");

                            t.HasCheckConstraint("ck_character_vitals_resource_non_negative", "\"CurrentResource\" >= 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Combat.ActiveCombatSession", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("BalanceVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TerminalSnapshotJson")
                        .HasColumnType("jsonb");

                    b.HasKey("SessionId", "CharacterId")
                        .HasName("pk_active_combat_sessions");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("uq_active_combat_sessions_character_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_active_combat_sessions_session_id");

                    b.HasIndex("StartedAtUtc")
                        .HasDatabaseName("ix_active_combat_sessions_started_at_utc");

                    b.ToTable("active_combat_sessions", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Combat.CharacterAbilityCooldown", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("AbilityId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ReadyAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CharacterId", "AbilityId")
                        .HasName("pk_character_ability_cooldowns");

                    b.HasIndex("ReadyAtUtc")
                        .HasDatabaseName("ix_character_ability_cooldowns_ready_at_utc");

                    b.ToTable("character_ability_cooldowns", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Combat.CombatConsumableUse", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CommandId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MaxStack")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SessionId", "CommandId")
                        .HasName("pk_combat_consumable_uses");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_combat_consumable_uses_character_id");

                    b.HasIndex("SessionId", "CharacterId");

                    b.ToTable("combat_consumable_uses", "game", t =>
                        {
                            t.HasCheckConstraint("ck_combat_consumable_uses_definition_version", "\"DefinitionVersion\" > 0");

                            t.HasCheckConstraint("ck_combat_consumable_uses_max_stack", "\"MaxStack\" >= 2");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Combat.CombatLootRoll", b =>
                {
                    b.Property<Guid>("LootRollId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChoicesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("CombatSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DungeonRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("EligibleCharacterIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GeneratedItemJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ItemInstanceSeed")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RollsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceQualityProfileId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("NORMAL");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("WinnerCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("LootRollId")
                        .HasName("pk_combat_loot_rolls");

                    b.HasIndex("CombatSessionId", "ItemDefinitionId")
                        .IsUnique()
                        .HasDatabaseName("uq_combat_loot_rolls_session_item");

                    b.HasIndex("State", "EndsAtUtc")
                        .HasDatabaseName("ix_combat_loot_rolls_state_ends_at_utc");

                    b.ToTable("combat_loot_rolls", "game", t =>
                        {
                            t.HasCheckConstraint("ck_combat_loot_rolls_quantity_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Combat.CombatSharedLootResolution", b =>
                {
                    b.Property<Guid>("CombatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GroupLootJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CombatSessionId")
                        .HasName("pk_combat_shared_loot_resolutions");

                    b.ToTable("combat_shared_loot_resolutions", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_content_audit_entries");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_content_audit_entries_occurred_at");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_content_audit_entries_release_id");

                    b.HasIndex("RevisionId")
                        .HasDatabaseName("ix_content_audit_entries_revision_id");

                    b.ToTable("content_audit_entries", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_content_releases");

                    b.HasIndex("PublishedAtUtc")
                        .HasDatabaseName("ix_content_releases_published_at");

                    b.HasIndex("RevisionId", "PublishedAtUtc")
                        .HasDatabaseName("ix_content_releases_revision_published_at");

                    b.ToTable("content_releases", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BalanceVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("SourcePublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("pk_content_revisions");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_content_revisions_created_at");

                    b.HasIndex("PayloadSha256")
                        .HasDatabaseName("ix_content_revisions_payload_sha256");

                    b.HasIndex("ContentVersion", "BalanceVersion")
                        .HasDatabaseName("ix_content_revisions_versions");

                    b.ToTable("content_revisions", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Dungeons.DungeonEncounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CombatSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EncounterIndex")
                        .HasColumnType("integer");

                    b.Property<string>("MonsterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("WipeCount")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_dungeon_encounters");

                    b.HasIndex("CombatSessionId")
                        .HasDatabaseName("ix_dungeon_encounters_combat_session_id");

                    b.HasIndex("RunId", "EncounterIndex")
                        .IsUnique()
                        .HasDatabaseName("uq_dungeon_encounters_run_index");

                    b.ToTable("dungeon_encounters", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Dungeons.DungeonEncounterMember", b =>
                {
                    b.Property<Guid>("EncounterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EncounterId", "CharacterId")
                        .HasName("pk_dungeon_encounter_members");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_dungeon_encounter_members_character_id");

                    b.ToTable("dungeon_encounter_members", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Dungeons.DungeonRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreationRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentEncounterIndex")
                        .HasColumnType("integer");

                    b.Property<string>("DungeonId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id")
                        .HasName("pk_dungeon_runs");

                    b.HasIndex("CreationRequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_dungeon_runs_creation_request_id");

                    b.HasIndex("PartyId", "State")
                        .HasDatabaseName("ix_dungeon_runs_party_state");

                    b.ToTable("dungeon_runs", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Dungeons.DungeonRunMember", b =>
                {
                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("RunId", "CharacterId")
                        .HasName("pk_dungeon_run_members");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_dungeon_run_members_character_id");

                    b.ToTable("dungeon_run_members", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Economy.CrystalLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Delta")
                        .HasColumnType("bigint");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id")
                        .HasName("pk_crystal_ledger_entries");

                    b.HasIndex("AccountId", "CreatedAtUtc")
                        .HasDatabaseName("ix_crystal_ledger_entries_account_created_at");

                    b.HasIndex("AccountId", "OperationId")
                        .IsUnique()
                        .HasDatabaseName("uq_crystal_ledger_entries_account_operation");

                    b.ToTable("crystal_ledger_entries", "game", t =>
                        {
                            t.HasCheckConstraint("ck_crystal_ledger_entries_balance_after_non_negative", "\"BalanceAfter\" >= 0");

                            t.HasCheckConstraint("ck_crystal_ledger_entries_delta_non_zero", "\"Delta\" <> 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Economy.CrystalWallet", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<long>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.HasKey("AccountId")
                        .HasName("pk_crystal_wallets");

                    b.ToTable("crystal_wallets", "game", t =>
                        {
                            t.HasCheckConstraint("ck_crystal_wallets_balance_non_negative", "\"Balance\" >= 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Economy.PremiumStorePurchase", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<long>("CrystalPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("PurchasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OperationId")
                        .HasName("pk_premium_store_purchases");

                    b.HasIndex("AccountId", "Sku")
                        .HasDatabaseName("ix_premium_store_purchases_account_sku");

                    b.ToTable("premium_store_purchases", "game", t =>
                        {
                            t.HasCheckConstraint("ck_premium_store_purchases_price_positive", "\"CrystalPrice\" > 0");

                            t.HasCheckConstraint("ck_premium_store_purchases_quantity_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Economy.PromoCodeRedemption", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RedeemedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("OperationId")
                        .HasName("pk_promo_code_redemptions");

                    b.HasIndex("CharacterId");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_promo_code_redemptions_code");

                    b.HasIndex("AccountId", "Code")
                        .HasDatabaseName("ix_promo_code_redemptions_account_code");

                    b.ToTable("promo_code_redemptions", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedTelegramUsername")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(33)
                        .HasColumnType("character varying(33)");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("NormalizedTelegramUsername")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_normalized_telegram_username");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_telegram_user_id");

                    b.ToTable("accounts", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Items.CharacterEquipment", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slot")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("CharacterItemId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "Slot")
                        .HasName("pk_character_equipment");

                    b.HasIndex("CharacterItemId")
                        .IsUnique()
                        .HasDatabaseName("uq_character_equipment_item_id");

                    b.ToTable("character_equipment", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Items.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ActualItemPower")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("BindState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasDefaultValue("UNBOUND");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("DefinitionVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("EnhancementLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("GeneratedDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("GeneratedPrefixId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("GeneratedSuffixId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("GenerationSeedHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("GenerationVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPerfect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ItemLevel")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxTemplateItemPower")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("MinimumTemplateItemPower")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("PerfectOrigin")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ReforgeCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ReforgeSlotKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("RollQuality")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal?>("RolledAgility")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("RolledIntellect")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("RolledStamina")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("RolledStrength")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("SourceEntryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("SourceOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("Stars")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TransactionLockId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_character_items");

                    b.HasIndex("SourceOperationId")
                        .HasDatabaseName("ix_character_items_source_operation");

                    b.HasIndex("TransactionLockId")
                        .HasDatabaseName("ix_character_items_transaction_lock");

                    b.HasIndex("CharacterId", "ItemDefinitionId")
                        .HasDatabaseName("ix_character_items_character_definition");

                    b.ToTable("character_items", "game", t =>
                        {
                            t.HasCheckConstraint("ck_character_items_quantity_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Items.ItemReforgeOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CatalystItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("CatalystQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("CostGold")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentItemJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MaterialQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ProposedItemJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SlotKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("OperationId")
                        .HasName("pk_item_reforge_operations");

                    b.HasIndex("ItemInstanceId")
                        .HasDatabaseName("ix_item_reforge_operations_item_id");

                    b.HasIndex("CharacterId", "ItemInstanceId", "State")
                        .HasDatabaseName("ix_item_reforge_operations_character_item_state");

                    b.ToTable("item_reforge_operations", "game", t =>
                        {
                            t.HasCheckConstraint("ck_item_reforge_operations_catalyst_quantity", "\"CatalystQuantity\" >= 0");

                            t.HasCheckConstraint("ck_item_reforge_operations_cost_gold", "\"CostGold\" >= 0");

                            t.HasCheckConstraint("ck_item_reforge_operations_material_quantity", "\"MaterialQuantity\" >= 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Items.ItemRolledAffix", b =>
                {
                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SlotKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AffixDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AffixTier")
                        .HasColumnType("integer");

                    b.Property<int>("GenerationOrdinal")
                        .HasColumnType("integer");

                    b.Property<bool>("IsGuaranteed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReforgeSlot")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxAtGeneration")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("MinAtGeneration")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("StatId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("StepAtGeneration")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("ItemInstanceId", "SlotKey")
                        .HasName("pk_character_item_affixes");

                    b.HasIndex("ItemInstanceId")
                        .HasDatabaseName("ix_character_item_affixes_item_id");

                    b.HasIndex("StatId")
                        .HasDatabaseName("ix_character_item_affixes_stat_id");

                    b.ToTable("character_item_affixes", "game", t =>
                        {
                            t.HasCheckConstraint("ck_character_item_affixes_range", "\"MaxAtGeneration\" >= \"MinAtGeneration\"");

                            t.HasCheckConstraint("ck_character_item_affixes_step_positive", "\"StepAtGeneration\" > 0");

                            t.HasCheckConstraint("ck_character_item_affixes_value_range", "\"Value\" >= \"MinAtGeneration\" AND \"Value\" <= \"MaxAtGeneration\"");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Items.ItemSalvageOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("MaterialQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ReforgeStoneItemId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("ReforgeStoneQuantity")
                        .HasColumnType("integer");

                    b.HasKey("OperationId")
                        .HasName("pk_item_salvage_operations");

                    b.HasIndex("CharacterId", "ItemInstanceId")
                        .HasDatabaseName("ix_item_salvage_operations_character_item");

                    b.ToTable("item_salvage_operations", "game", t =>
                        {
                            t.HasCheckConstraint("ck_item_salvage_operations_material", "\"MaterialQuantity\" >= 0");

                            t.HasCheckConstraint("ck_item_salvage_operations_stones", "\"ReforgeStoneQuantity\" > 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Items.PendingLootItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("GeneratedItemJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("GenerationSeedHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RewardResolutionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RolledAgility")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("RolledIntellect")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("RolledStamina")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("RolledStrength")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("SourceEntryId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("SourceOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id")
                        .HasName("pk_pending_loot_items");

                    b.HasIndex("RewardResolutionId")
                        .HasDatabaseName("ix_pending_loot_items_reward_resolution_id");

                    b.HasIndex("CharacterId", "CreatedAtUtc")
                        .HasDatabaseName("ix_pending_loot_items_character_created_at");

                    b.ToTable("pending_loot_items", "game", t =>
                        {
                            t.HasCheckConstraint("ck_pending_loot_items_quantity_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Parties.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreationRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LeaderCharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_parties");

                    b.HasIndex("CreationRequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_parties_creation_request_id");

                    b.HasIndex("LeaderCharacterId")
                        .HasDatabaseName("ix_parties_leader_character_id");

                    b.ToTable("parties", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Parties.PartyInvite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InviterCharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Mode")
                        .HasColumnType("integer");

                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_party_invites");

                    b.HasIndex("InviterCharacterId");

                    b.HasIndex("PartyId");

                    b.HasIndex("TargetCharacterId", "Status")
                        .HasDatabaseName("ix_party_invites_target_status");

                    b.ToTable("party_invites", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Parties.PartyMember", b =>
                {
                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("PartyId", "CharacterId")
                        .HasName("pk_party_members");

                    b.HasIndex("CharacterId")
                        .IsUnique()
                        .HasDatabaseName("uq_party_members_character_id");

                    b.ToTable("party_members", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Progression.CombatRewardGrant", b =>
                {
                    b.Property<Guid>("CombatSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("GoldEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrimaryMonsterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("MonsterId");

                    b.Property<string>("RewardSourcesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValueSql("'[]'::jsonb");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("CombatSessionId", "CharacterId")
                        .HasName("pk_combat_reward_grants");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_combat_reward_grants_character_id");

                    b.ToTable("combat_reward_grants", "game", t =>
                        {
                            t.HasCheckConstraint("ck_combat_reward_grants_gold_non_negative", "\"GoldEarned\" >= 0");

                            t.HasCheckConstraint("ck_combat_reward_grants_sources_json", "jsonb_typeof(\"RewardSourcesJson\") = 'array'");

                            t.HasCheckConstraint("ck_combat_reward_grants_xp_non_negative", "\"XpEarned\" >= 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Quests.CharacterQuestState", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProgressJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("ReadyAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("StateVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("CharacterId", "QuestId")
                        .HasName("pk_character_quest_states");

                    b.HasIndex("CharacterId", "Status")
                        .HasDatabaseName("ix_character_quest_states_character_status");

                    b.ToTable("character_quest_states", "game", t =>
                        {
                            t.HasCheckConstraint("ck_character_quest_states_progress_json", "jsonb_typeof(\"ProgressJson\") = 'object'");

                            t.HasCheckConstraint("ck_character_quest_states_status", "\"Status\" IN ('ACTIVE','READY_TO_CLAIM','COMPLETED')");

                            t.HasCheckConstraint("ck_character_quest_states_version_positive", "\"StateVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Quests.QuestRewardGrant", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ClaimMutationId")
                        .HasColumnType("uuid");

                    b.Property<int>("GoldEarned")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RewardItemsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId", "QuestId")
                        .HasName("pk_quest_reward_grants");

                    b.HasIndex("ClaimMutationId")
                        .IsUnique()
                        .HasDatabaseName("uq_quest_reward_grants_claim_mutation_id");

                    b.ToTable("quest_reward_grants", "game", t =>
                        {
                            t.HasCheckConstraint("ck_quest_reward_grants_gold_non_negative", "\"GoldEarned\" >= 0");

                            t.HasCheckConstraint("ck_quest_reward_grants_items_json", "jsonb_typeof(\"RewardItemsJson\") = 'array'");

                            t.HasCheckConstraint("ck_quest_reward_grants_xp_non_negative", "\"XpEarned\" >= 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Social.FriendRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DecidedByCharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("PairKey")
                        .IsRequired()
                        .HasMaxLength(73)
                        .HasColumnType("character varying(73)");

                    b.Property<Guid>("RequesterCharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetCharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_friend_requests");

                    b.HasIndex("RequesterCharacterId");

                    b.HasIndex("TargetCharacterId")
                        .HasDatabaseName("ix_friend_requests_target_character_id");

                    b.HasIndex("PairKey", "Status")
                        .IsUnique()
                        .HasDatabaseName("uq_friend_requests_pending_pair")
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("friend_requests", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Social.Friendship", b =>
                {
                    b.Property<string>("PairKey")
                        .HasMaxLength(73)
                        .HasColumnType("character varying(73)");

                    b.Property<Guid>("CharacterAId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterBId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PairKey")
                        .HasName("pk_friendships");

                    b.HasIndex("CharacterAId")
                        .HasDatabaseName("ix_friendships_character_a_id");

                    b.HasIndex("CharacterBId")
                        .HasDatabaseName("ix_friendships_character_b_id");

                    b.ToTable("friendships", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Talents.CharacterTalentState", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveLoadoutId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMutationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Loadout1RanksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Loadout2RanksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("StateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("TalentTreeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TalentVersion")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId")
                        .HasName("pk_character_talent_states");

                    b.ToTable("character_talent_states", "game", t =>
                        {
                            t.HasCheckConstraint("ck_character_talent_states_active_loadout", "\"ActiveLoadoutId\" IN ('LOADOUT_1', 'LOADOUT_2')");

                            t.HasCheckConstraint("ck_character_talent_states_loadout_1_json", "jsonb_typeof(\"Loadout1RanksJson\") = 'object'");

                            t.HasCheckConstraint("ck_character_talent_states_loadout_2_json", "jsonb_typeof(\"Loadout2RanksJson\") = 'object'");

                            t.HasCheckConstraint("ck_character_talent_states_state_version", "\"StateVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterContractAcceptance", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CharacterId", "ContractId")
                        .HasName("pk_character_contract_acceptances");

                    b.ToTable("character_contract_acceptances", "game");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterContractCompletion", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContractId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("CombatSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetMonsterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CharacterId", "ContractId")
                        .HasName("pk_character_contract_completions");

                    b.HasIndex("CombatSessionId")
                        .HasDatabaseName("ix_character_contract_completions_combat_session_id");

                    b.ToTable("character_contract_completions", "game");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterLocation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("CharacterId")
                        .HasName("pk_character_locations");

                    b.ToTable("character_locations", "game");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterTravelState", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromLocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetLocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CharacterId")
                        .HasName("pk_character_travel_states");

                    b.HasIndex("EndsAtUtc")
                        .HasDatabaseName("ix_character_travel_states_ends_at_utc");

                    b.HasIndex("CharacterId", "RequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_character_travel_states_character_request");

                    b.ToTable("character_travel_states", "game", t =>
                        {
                            t.HasCheckConstraint("ck_character_travel_states_duration", "\"EndsAtUtc\" > \"StartedAtUtc\"");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.World.TravelOperation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultLocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ResultVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetLocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CharacterId", "RequestId")
                        .HasName("pk_travel_operations");

                    b.ToTable("travel_operations", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Afk.AfkFarmIntervalGrant", b =>
                {
                    b.HasOne("Elyndor.Core.Afk.AfkFarmSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_afk_farm_interval_grants_sessions_session_id");
                });

            modelBuilder.Entity("Elyndor.Core.Afk.AfkFarmSession", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_afk_farm_sessions_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Characters.Character", b =>
                {
                    b.HasOne("Elyndor.Core.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_accounts_account_id");
                });

            modelBuilder.Entity("Elyndor.Core.Characters.CharacterMutation", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_mutations_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Characters.CharacterVitals", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("Elyndor.Core.Characters.CharacterVitals", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_vitals_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Combat.ActiveCombatSession", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("Elyndor.Core.Combat.ActiveCombatSession", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_active_combat_sessions_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Combat.CharacterAbilityCooldown", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_ability_cooldowns_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Combat.CombatConsumableUse", b =>
                {
                    b.HasOne("Elyndor.Core.Combat.ActiveCombatSession", null)
                        .WithMany()
                        .HasForeignKey("SessionId", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_combat_consumable_uses_active_combat_session");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentAuditEntry", b =>
                {
                    b.HasOne("Elyndor.Core.Content.ContentRelease", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_audit_entries_content_releases_release_id");

                    b.HasOne("Elyndor.Core.Content.ContentRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_audit_entries_content_revisions_revision_id");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentRelease", b =>
                {
                    b.HasOne("Elyndor.Core.Content.ContentRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_releases_content_revisions_revision_id");
                });

            modelBuilder.Entity("Elyndor.Core.Dungeons.DungeonEncounter", b =>
                {
                    b.HasOne("Elyndor.Core.Dungeons.DungeonRun", "Run")
                        .WithMany("Encounters")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Elyndor.Core.Dungeons.DungeonEncounterMember", b =>
                {
                    b.HasOne("Elyndor.Core.Dungeons.DungeonEncounter", null)
                        .WithMany("Members")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elyndor.Core.Dungeons.DungeonRunMember", b =>
                {
                    b.HasOne("Elyndor.Core.Dungeons.DungeonRun", null)
                        .WithMany("Members")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Elyndor.Core.Economy.CrystalLedgerEntry", b =>
                {
                    b.HasOne("Elyndor.Core.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crystal_ledger_entries_accounts_account_id");
                });

            modelBuilder.Entity("Elyndor.Core.Economy.CrystalWallet", b =>
                {
                    b.HasOne("Elyndor.Core.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_crystal_wallets_accounts_account_id");
                });

            modelBuilder.Entity("Elyndor.Core.Economy.PromoCodeRedemption", b =>
                {
                    b.HasOne("Elyndor.Core.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promo_code_redemptions_accounts_account_id");

                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promo_code_redemptions_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Items.CharacterEquipment", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_equipment_characters_character_id");

                    b.HasOne("Elyndor.Core.Items.CharacterItem", null)
                        .WithMany()
                        .HasForeignKey("CharacterItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_equipment_character_items_item_id");
                });

            modelBuilder.Entity("Elyndor.Core.Items.CharacterItem", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_items_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Items.ItemRolledAffix", b =>
                {
                    b.HasOne("Elyndor.Core.Items.CharacterItem", null)
                        .WithMany("Affixes")
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_item_affixes_character_items_item_id");
                });

            modelBuilder.Entity("Elyndor.Core.Items.PendingLootItem", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pending_loot_items_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Parties.Party", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("LeaderCharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_parties_leader_character");
                });

            modelBuilder.Entity("Elyndor.Core.Parties.PartyInvite", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("InviterCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_invites_inviter_character_id");

                    b.HasOne("Elyndor.Core.Parties.Party", null)
                        .WithMany()
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_invites_party_id");

                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_invites_target_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Parties.PartyMember", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_members_character_id");

                    b.HasOne("Elyndor.Core.Parties.Party", null)
                        .WithMany("Members")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_party_members_parties_party_id");
                });

            modelBuilder.Entity("Elyndor.Core.Progression.CombatRewardGrant", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_combat_reward_grants_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Quests.CharacterQuestState", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_quest_states_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Quests.QuestRewardGrant", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_reward_grants_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Social.FriendRequest", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("RequesterCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friend_requests_requester_character");

                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("TargetCharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friend_requests_target_character");
                });

            modelBuilder.Entity("Elyndor.Core.Social.Friendship", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterAId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_character_a");

                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterBId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_friendships_character_b");
                });

            modelBuilder.Entity("Elyndor.Core.Talents.CharacterTalentState", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("Elyndor.Core.Talents.CharacterTalentState", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_talent_states_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterContractAcceptance", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_contract_acceptances_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterContractCompletion", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_contract_completions_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterLocation", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("Elyndor.Core.World.CharacterLocation", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_locations_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterTravelState", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("Elyndor.Core.World.CharacterTravelState", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_travel_states_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.World.TravelOperation", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_travel_operations_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Dungeons.DungeonEncounter", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Elyndor.Core.Dungeons.DungeonRun", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Elyndor.Core.Items.CharacterItem", b =>
                {
                    b.Navigation("Affixes");
                });

            modelBuilder.Entity("Elyndor.Core.Parties.Party", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
