// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Elyndor.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class PlayerCommerceSettlement : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Storage",
                schema: "game",
                table: "character_items",
                type: "character varying(16)",
                maxLength: 16,
                nullable: false,
                defaultValue: "INVENTORY");

            migrationBuilder.CreateTable(
                name: "auction_listings",
                schema: "game",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    SellerId = table.Column<Guid>(type: "uuid", nullable: false),
                    ItemId = table.Column<Guid>(type: "uuid", nullable: false),
                    Price = table.Column<long>(type: "bigint", nullable: false),
                    Fee = table.Column<long>(type: "bigint", nullable: false),
                    Tax = table.Column<long>(type: "bigint", nullable: false),
                    State = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                    BuyerId = table.Column<Guid>(type: "uuid", nullable: true),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    ExpiresAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    SettledAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_auction_listings", x => x.Id);
                    table.CheckConstraint("ck_auction_amounts", "\"Price\" > 0 AND \"Fee\" >= 0 AND \"Tax\" >= 0 AND \"Tax\" <= \"Price\"");
                    table.ForeignKey(
                        name: "FK_auction_listings_characters_BuyerId",
                        column: x => x.BuyerId,
                        principalSchema: "game",
                        principalTable: "characters",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_auction_listings_characters_SellerId",
                        column: x => x.SellerId,
                        principalSchema: "game",
                        principalTable: "characters",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "commerce_mail",
                schema: "game",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CharacterId = table.Column<Guid>(type: "uuid", nullable: false),
                    ItemId = table.Column<Guid>(type: "uuid", nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    ClaimedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_commerce_mail", x => x.Id);
                    table.ForeignKey(
                        name: "FK_commerce_mail_characters_CharacterId",
                        column: x => x.CharacterId,
                        principalSchema: "game",
                        principalTable: "characters",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "player_trades",
                schema: "game",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    CharacterAId = table.Column<Guid>(type: "uuid", nullable: false),
                    CharacterBId = table.Column<Guid>(type: "uuid", nullable: false),
                    State = table.Column<string>(type: "character varying(16)", maxLength: 16, nullable: false),
                    Revision = table.Column<int>(type: "integer", nullable: false),
                    ItemsA = table.Column<Guid[]>(type: "uuid[]", nullable: false),
                    ItemsB = table.Column<Guid[]>(type: "uuid[]", nullable: false),
                    GoldA = table.Column<long>(type: "bigint", nullable: false),
                    GoldB = table.Column<long>(type: "bigint", nullable: false),
                    LockedA = table.Column<bool>(type: "boolean", nullable: false),
                    LockedB = table.Column<bool>(type: "boolean", nullable: false),
                    ConfirmedA = table.Column<bool>(type: "boolean", nullable: false),
                    ConfirmedB = table.Column<bool>(type: "boolean", nullable: false),
                    ConnectionA = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    ConnectionB = table.Column<string>(type: "character varying(128)", maxLength: 128, nullable: true),
                    ExpiresAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_player_trades", x => x.Id);
                    table.CheckConstraint("ck_trade_gold", "\"GoldA\" >= 0 AND \"GoldB\" >= 0 AND \"CharacterAId\" <> \"CharacterBId\"");
                    table.ForeignKey(
                        name: "FK_player_trades_characters_CharacterAId",
                        column: x => x.CharacterAId,
                        principalSchema: "game",
                        principalTable: "characters",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_player_trades_characters_CharacterBId",
                        column: x => x.CharacterBId,
                        principalSchema: "game",
                        principalTable: "characters",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_auction_listings_BuyerId",
                schema: "game",
                table: "auction_listings",
                column: "BuyerId");

            migrationBuilder.CreateIndex(
                name: "IX_auction_listings_ItemId",
                schema: "game",
                table: "auction_listings",
                column: "ItemId",
                unique: true,
                filter: "\"State\" = 'ACTIVE'");

            migrationBuilder.CreateIndex(
                name: "IX_auction_listings_SellerId",
                schema: "game",
                table: "auction_listings",
                column: "SellerId");

            migrationBuilder.CreateIndex(
                name: "IX_auction_listings_State_ExpiresAt",
                schema: "game",
                table: "auction_listings",
                columns: new[] { "State", "ExpiresAt" });

            migrationBuilder.CreateIndex(
                name: "IX_commerce_mail_CharacterId_ClaimedAt",
                schema: "game",
                table: "commerce_mail",
                columns: new[] { "CharacterId", "ClaimedAt" });

            migrationBuilder.CreateIndex(
                name: "IX_commerce_mail_ItemId",
                schema: "game",
                table: "commerce_mail",
                column: "ItemId",
                unique: true,
                filter: "\"ClaimedAt\" IS NULL");

            migrationBuilder.CreateIndex(
                name: "IX_player_trades_CharacterAId",
                schema: "game",
                table: "player_trades",
                column: "CharacterAId");

            migrationBuilder.CreateIndex(
                name: "IX_player_trades_CharacterBId",
                schema: "game",
                table: "player_trades",
                column: "CharacterBId");

            migrationBuilder.CreateIndex(
                name: "IX_player_trades_State_ExpiresAt",
                schema: "game",
                table: "player_trades",
                columns: new[] { "State", "ExpiresAt" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "auction_listings",
                schema: "game");

            migrationBuilder.DropTable(
                name: "commerce_mail",
                schema: "game");

            migrationBuilder.DropTable(
                name: "player_trades",
                schema: "game");

            migrationBuilder.DropColumn(
                name: "Storage",
                schema: "game",
                table: "character_items");
        }
    }
}
