// <auto-generated />
using System;
using Elyndor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Elyndor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("game")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Elyndor.Core.Administration.AdminCommandAudit", b =>
                {
                    b.Property<long>("UpdateId")
                        .HasColumnType("bigint");

                    b.Property<long>("AdministratorTelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("CommandName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<long?>("TargetTelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("UpdateId")
                        .HasName("pk_admin_command_audits");

                    b.HasIndex("AdministratorTelegramUserId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_admin_command_audits_administrator_received_at");

                    b.HasIndex("TargetTelegramUserId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_admin_command_audits_target_received_at");

                    b.ToTable("admin_command_audits", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Characters.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreationRequestId")
                        .HasColumnType("uuid");

                    b.Property<long>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("GenderId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("Gold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RaceId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_account_id");

                    b.HasIndex("CreationRequestId")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_creation_request_id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("uq_characters_normalized_name");

                    b.ToTable("characters", "game", t =>
                        {
                            t.HasCheckConstraint("ck_characters_experience_non_negative", "\"Experience\" >= 0");

                            t.HasCheckConstraint("ck_characters_gold_non_negative", "\"Gold\" >= 0");
                        });
                });


            modelBuilder.Entity("Elyndor.Core.Characters.CharacterMutation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MutationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CommittedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CharacterId", "MutationId")
                        .HasName("pk_character_mutations");

                    b.HasIndex("CharacterId", "CommittedAtUtc")
                        .HasDatabaseName("ix_character_mutations_character_committed_at");

                    b.ToTable("character_mutations", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Characters.CharacterVitals", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CheckpointedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ContextStartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentHp")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.Property<decimal>("CurrentResource")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)");

                    b.HasKey("CharacterId")
                        .HasName("pk_character_vitals");

                    b.ToTable("character_vitals", "game", t =>
                        {
                            t.HasCheckConstraint("ck_character_vitals_hp_non_negative", "\"CurrentHp\" >= 0");

                            t.HasCheckConstraint("ck_character_vitals_resource_non_negative", "\"CurrentResource\" >= 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Identity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("pk_accounts");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_accounts_telegram_user_id");

                    b.ToTable("accounts", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Items.CharacterEquipment", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slot")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid>("CharacterItemId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "Slot")
                        .HasName("pk_character_equipment");

                    b.HasIndex("CharacterItemId")
                        .IsUnique()
                        .HasDatabaseName("uq_character_equipment_item_id");

                    b.ToTable("character_equipment", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Items.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ItemDefinitionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_character_items");

                    b.HasIndex("CharacterId", "ItemDefinitionId")
                        .HasDatabaseName("ix_character_items_character_definition");

                    b.ToTable("character_items", "game", t =>
                        {
                            t.HasCheckConstraint("ck_character_items_quantity_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Progression.CombatRewardGrant", b =>
                {
                    b.Property<Guid>("CombatSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("GoldEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("GrantedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MonsterId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("CombatSessionId")
                        .HasName("pk_combat_reward_grants");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_combat_reward_grants_character_id");

                    b.ToTable("combat_reward_grants", "game", t =>
                        {
                            t.HasCheckConstraint("ck_combat_reward_grants_gold_non_negative", "\"GoldEarned\" >= 0");

                            t.HasCheckConstraint("ck_combat_reward_grants_xp_non_negative", "\"XpEarned\" >= 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.Talents.CharacterTalentState", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveLoadoutId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastMutationId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Loadout1RanksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Loadout2RanksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("StateVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("TalentTreeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TalentVersion")
                        .HasColumnType("integer");

                    b.HasKey("CharacterId")
                        .HasName("pk_character_talent_states");

                    b.ToTable("character_talent_states", "game", t =>
                        {
                            t.HasCheckConstraint("ck_character_talent_states_active_loadout", "\"ActiveLoadoutId\" IN ('LOADOUT_1', 'LOADOUT_2')");

                            t.HasCheckConstraint("ck_character_talent_states_loadout_1_json", "jsonb_typeof(\"Loadout1RanksJson\") = 'object'");

                            t.HasCheckConstraint("ck_character_talent_states_loadout_2_json", "jsonb_typeof(\"Loadout2RanksJson\") = 'object'");

                            t.HasCheckConstraint("ck_character_talent_states_state_version", "\"StateVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterLocation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("CharacterId")
                        .HasName("pk_character_locations");

                    b.ToTable("character_locations", "game");
                });

            modelBuilder.Entity("Elyndor.Core.World.TravelOperation", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResultLocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("ResultVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetLocationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CharacterId", "RequestId")
                        .HasName("pk_travel_operations");

                    b.ToTable("travel_operations", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_content_audit_entries");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_content_audit_entries_occurred_at");

                    b.HasIndex("ReleaseId")
                        .HasDatabaseName("ix_content_audit_entries_release_id");

                    b.HasIndex("RevisionId")
                        .HasDatabaseName("ix_content_audit_entries_revision_id");

                    b.ToTable("content_audit_entries", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublishedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("pk_content_releases");

                    b.HasIndex("PublishedAtUtc")
                        .HasDatabaseName("ix_content_releases_published_at");

                    b.HasIndex("RevisionId", "PublishedAtUtc")
                        .HasDatabaseName("ix_content_releases_revision_published_at");

                    b.ToTable("content_releases", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BalanceVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Note")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("PayloadSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("SourcePublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("pk_content_revisions");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_content_revisions_created_at");

                    b.HasIndex("PayloadSha256")
                        .HasDatabaseName("ix_content_revisions_payload_sha256");

                    b.HasIndex("ContentVersion", "BalanceVersion")
                        .HasDatabaseName("ix_content_revisions_versions");

                    b.ToTable("content_revisions", "game");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentAuditEntry", b =>
                {
                    b.HasOne("Elyndor.Core.Content.ContentRelease", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_audit_entries_content_releases_release_id");

                    b.HasOne("Elyndor.Core.Content.ContentRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_content_audit_entries_content_revisions_revision_id");
                });

            modelBuilder.Entity("Elyndor.Core.Content.ContentRelease", b =>
                {
                    b.HasOne("Elyndor.Core.Content.ContentRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_content_releases_content_revisions_revision_id");
                });

            modelBuilder.Entity("Elyndor.Core.Characters.Character", b =>
                {
                    b.HasOne("Elyndor.Core.Identity.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_accounts_account_id");
                });


            modelBuilder.Entity("Elyndor.Core.Characters.CharacterMutation", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_mutations_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Characters.CharacterVitals", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("Elyndor.Core.Characters.CharacterVitals", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_vitals_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Items.CharacterEquipment", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_equipment_characters_character_id");

                    b.HasOne("Elyndor.Core.Items.CharacterItem", null)
                        .WithMany()
                        .HasForeignKey("CharacterItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_equipment_character_items_item_id");
                });

            modelBuilder.Entity("Elyndor.Core.Items.CharacterItem", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_items_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Progression.CombatRewardGrant", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_combat_reward_grants_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.Talents.CharacterTalentState", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("Elyndor.Core.Talents.CharacterTalentState", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_talent_states_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.World.CharacterLocation", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithOne()
                        .HasForeignKey("Elyndor.Core.World.CharacterLocation", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_character_locations_characters_character_id");
                });

            modelBuilder.Entity("Elyndor.Core.World.TravelOperation", b =>
                {
                    b.HasOne("Elyndor.Core.Characters.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_travel_operations_characters_character_id");
                });
#pragma warning restore 612, 618
        }
    }
}
